on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

name: "periodicos_pagina_instrucao"

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          needs: devtools

      - name: "Baixar página de instruções aos autores"
        run: Rscript data-raw/instrucoes_autores.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data-raw/dados_html/*
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
